<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{7ad81a30-7aa4-44e3-9151-5703448cad9a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	
END_VAR
 ]]></Declaration>
    <Implementation>
      <ST><![CDATA[
POU_Seguridad();
POU_Mando();
POU_Funcionamiento();

]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="670" Count="0" />
      <LineId Id="1010" Count="1" />
      <LineId Id="977" Count="1" />
      <LineId Id="195" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>